[package]
name = "netune"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
base64 = { workspace = true }
brotli = { workspace = true }
bytes = { workspace = true }
flate2 = { workspace = true }
http = { workspace = true }
libc = { workspace = true }
netune-http1 = { path = "../netune-http1" }
netune-trace = { path = "../netune-trace" }
rustls = { workspace = true }
rustls-platform-verifier = { workspace = true }
tokio = { workspace = true, features = ["net", "io-util", "time", "sync", "rt"] }
tokio-rustls = { workspace = true }

[dev-dependencies]
base64 = { workspace = true }
brotli = { workspace = true }
flate2 = { workspace = true }
http = { workspace = true }
netune-trace = { path = "../netune-trace" }
rcgen = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "net", "io-util", "time"] }

[lints]
workspace = true
